### ISSUE TITLE
Allow omitting org-generate-root

### ISSUE THREAD

**Issue by akirak** [conao3/org-generate.el#1]
Hello, I've found this package in a reddit thread, and I'm glad to see you've created another project that would cover one of the features of [my ceased one](https://github.com/akirak/melpa-check/tree/v3#typical-project-structure)!

This project will be more useful if it supports multiple configuration files, as suggested by riscy in [this comment](https://github.com/melpa/melpa/pull/6977#issuecomment-647177666). 

Would you support configuration files without `org-generate-root` property (or allow parameters in it)? Because file paths like `~/dev/repos/hugo-src/content/blog/` are quite personal, I think this feature is essential if users share files with others.

**Comment by conao3** [comment]
Thanks. But I can't grasp what you want.

https://github.com/conao3/org-generate.el#define-one-file-template

> In this way, you can specify where to extract the template by default via setting org-generate-root in properties. If you omit it, you can specify it when you unpack the template.

This behavior is not thing that you want?

**Comment by akirak** [comment]
Is it possible to include a variable in `org-generate-root`? For example, one may have a hugo project in somewhere other than `~/dev/repos/hugo-src/`. If you want to develop community templates, it would be important to allow customizing/personalizing the directory organization.

**Comment by conao3** [comment]
Just delete `org-generate-root` field, `org-generate` ask you directory to expand the template tree. It is thing you want, isn't it?

**Comment by akirak** [comment]
I know that, but it wouldn't allow sharing templates in a version-controlled repository. Thanks.

**Comment by conao3** [comment]
> I know that, but it wouldn't allow sharing templates in a version-controlled repository.

VC repository? I can't grasp your mentioned situation. Please tell me a more concrete one?

**Comment by akirak** [comment]
I'm talking about this feature in the riscy's comment:

> I wonder if it would be a valuable service to have this come with a generators/ subdirectory with a bunch of standardized generators that you could open up to the community for contributions (elisp project generators, latex document generators, etc.)

It's not available in the current version, so I'm only talking about a possible feature.

**Comment by conao3** [comment]
If prepending `C-u`, force the user to input expand directory, I think it's practically possible.
Also potentially, by using `org-to-org`, it can combine multiple org-generate template definition files into a single file. https://github.com/conao3/org-generate.el/issues/3

**Comment by conao3** [comment]
Recently, #10 merged.
Please see this test case.
https://github.com/conao3/org-generate.el/blob/e516023bdfb02cd9768dcf3843d494392f85e054/org-generate-tests.el#L186-L213
Now you can use variable or interactive input as `org-generate-root`.
