### ISSUE TITLE
Support yasnippet templating syntax

### ISSUE THREAD

**Issue by akirak** [conao3/org-generate.el#2]
Would you plan on adding support for [yasnippet](https://github.com/joaotavora/yasnippet) templating syntax? 

This package currently supports the Mustache template syntax, but I am not used to it. This package is similar to [yankpad](https://github.com/Kungsgeten/yankpad) in that it lets you organize templates in an Org file, and it supports yasnippet snippets. This feature would allow the user to easily migrate from yasnippet/yankpad.

**Comment by conao3** [comment]
Yes, this is a good feature request.
Now, mustache.el could not write Elisp lambda in the template. [mustache issue](https://github.com/Wilfred/mustache.el/issues/10)
Sometimes I feel that mustache.el is lacking in functionality.

However, I have adopted mustache because it is necessary and sufficient.
The fact that all keys and values are mapped to each other before the template expanding allows for extremely fast to expand file templates.
Although yasnippet is useful, it is overly interactive for this purpose.

Perhaps we can share our goals by discussing more specific examples.

**Comment by hubisan** [comment]
An easy solution would be to have an org buffer, insert your org snippet and then call `org-generate` like this:

``` emacs-lisp
(defun my-org-generate-with-current-buffer ()
  (interactive)
  (let ((org-generate--file-buffer (current-buffer)))
    (call-interactively #'org-generate)))
```

Another approach (unfinished, could use a var for the target and a binding to finish it) is to insert the content for the org-generate file into a temp buffer and expand the targetted subtree with yas. To finish the above function needs to be called again.

``` emacs-lisp
(defun my-yas-expand-snippet (target)
  "Expand template of TARGET template with yas before calling `org-generate'."
  (interactive (list
                (completing-read
                 "Generate: "
                 (org-generate-candidate) nil 'match)))
  (let* ((gen-buf (org-generate-file-buffer))
         (buf-str (with-current-buffer gen-buf
                    (buffer-substring-no-properties (point-min) (point-max))))
         (heading (org-generate-search-heading target))
         (beg (plist-get (car (org-generate-search-heading target)) :begin))
         (end (1- (plist-get (car (org-generate-search-heading target)) :end)))
         (yas-str (with-current-buffer gen-buf
                    (buffer-substring-no-properties beg end)))
         (buf (generate-new-buffer "*org-generate-yas*")))
    (switch-to-buffer buf)
    (org-mode)
    (insert buf-str)
    (yas-expand-snippet yas-str beg end)))
```

Expanding the snippet inside the generate buffer is not a good idea as this would remove the snippet.

**Comment by akirak** [comment]
Thanks, I got it.

**Comment by conao3** [comment]
Recently, #10 is merged.
Please see this test case.
https://github.com/conao3/org-generate.el/blob/e516023bdfb02cd9768dcf3843d494392f85e054/org-generate-tests.el#L399-L462

Now you can use lambda or any language output. It is not `yasnippet` syntax, but this feature is much sufficient.
