### ISSUE TITLE
Export as org before generating

### ISSUE THREAD

**Issue by hubisan** [conao3/org-generate.el#3]
Just an idea: It would be quite cool to export the subtree as org before generating the template with

``` emacs-lisp
(org-org-export-as-org &optional ASYNC SUBTREEP VISIBLE-ONLY BODY-ONLY EXT-PLIST)
(org-org-export-as-org nil t nil t)
```
This would make it possible to use a lot of additional org features. The following come in to my mind but there are certainly many more:

-----------------------

### Macros

Use [macros](https://orgmode.org/manual/Macro-Replacement.html) to replace text snippets during export.

``` text
* Project template
:PROPERTIES:
:package:     test
:END:
#+MACRO: macro-input (eval (completing-read "Type: " '("First" "Second") nil t "First"))
#+MACRO: poem Rose is $1, violet's $2. Life's ordered: Org assists you.
{{{poem(red,blue)}}}
{{{macro-input}}}
{{{property(package)}}}
```
This lets the user select from First and Second and exports as:

``` text
#+macro: macro-input (eval (completing-read "Type: " '("First" "Second") nil t "First"))
#+macro: poem Rose is $1, violet's $2. Life's ordered: Org assists you.
Rose is red, violet's blue. Life's ordered: Org assists you.
First
test
```

_(only part disturbing is that the user-input macro is evaluated even if the expansion is not in the subtree, but could be solved by copying the subtree to another buffer first or whatever. Or of course let the user have an org file for each template.)_

-----------------------

### Include

Include other files:

``` text
#+INCLUDE: "~/dev/file-templates/GPLv3.txt"
```

-----------------------

#### Source block noweb

Include the code or the result of other source blocks with [noweb](https://orgmode.org/manual/Noweb-Reference-Syntax.html).

An example with a simple named block and a shell source block:

``` text
#+NAME: year
: 2020

#+NAME: whoami
#+BEGIN_SRC sh
  whoami
#+END_SRC

* Subtree
#+BEGIN_SRC emacs-lisp :noweb yes
  ; by <<whoami()>> in <<year()>>
#+END_SRC
```
Exports to in my case:

``` text
#+begin_src emacs-lisp
  ; by hubisan in 2020
#+end_src
```
Macros could be used as variables for the source blocks as far as I know.

#### Inlines source blocks

``` text
this is some src_elisp[:results raw]{(concat "inline" "-" "code")}
> this is some inline-code
```

#### Call on separate line or inline

The source block called can even be located in another files.

``` text
#+CALL: file.org:whoami()
my username is call_file.org:whoami()
```

**Comment by conao3** [comment]
It seems very interesting! Do you want to send PR?

**Comment by hubisan** [comment]
Will try to implement it, will take a while though as quite busy atm.

**Comment by conao3** [comment]
close with merging #10.
